# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/defa/avatar.jpg', max_length=200, upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
    ]
