# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171013_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='defa/avatar.jpg', max_length=200, upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
